[palettes.gruvbox_dark]
color_orange = '#4f4c67'
color_yellow = '#985f6e'
color_aqua = '#b486a0'
color_blue = '#a6b0e1'
color_bg3 = '#665c54'
color_bg1 = '#3c3836'
color_fg0 = '#fbf1c7'
color_green = '#98971a'
color_purple = '#b16286'
color_red = '#cc241d'